<!DOCTYPE Mechanics_Info [ <!ELEMENT Mechanics_Info (Mechanic)*>
<!ELEMENT Mechanic (name, details, role+, vehicles_serviced, is_servicing)>
<!ATTLIST Mechanic mechanic_id CDATA #REQUIRED>
<!ELEMENT mechanic_id (#PCDATA)>
<!ELEMENT name   (first_name,surname)>
		<!ELEMENT first_name (#PCDATA)>
		<!ELEMENT surname (#PCDATA)>
<!ELEMENT details (address, PPSN, phone_number, e-mail_address, bank_details)>
		<!ELEMENT address (number_or_name, street, town, postcode, county)>
				<!ELEMENT number_or_name (#PCDATA)>
				<!ELEMENT street (#PCDATA)>
				<!ELEMENT town (#PCDATA)>
				<!ELEMENT postcode (#PCDATA)>	
				<!ELEMENT county (#PCDATA)>
		<!ELEMENT PPSN (#PCDATA)>
		<!ELEMENT phone_number (#PCDATA)>
		<!ELEMENT e-mail_address (#PCDATA)>
		<!ELEMENT bank_details (IBAN, BIC)>
				<!ELEMENT IBAN (#PCDATA)>
				<!ELEMENT BIC (#PCDATA)>
<!ELEMENT role (#PCDATA)>
<!ELEMENT vehicles_serviced (Vehicle)*>
		<!ELEMENT Vehicle (type, last_service, needs_service, is_being_serviced)>
			<!ATTLIST Vehicle vehicle_id CDATA #REQUIRED>
			<!ELEMENT vehicle_id (#PCDATA)>
				<!ELEMENT type (#PCDATA)>	
				<!ELEMENT last_service (#PCDATA)>	
				<!ELEMENT needs_service (#PCDATA)>
				<!ELEMENT is_being_serviced (#PCDATA)>
<!ELEMENT is_servicing (#PCDATA)>]>

<Mechanics_Info>
  <Mechanic  mechanic_id="105">
    <name>
			<first_name>Brandon</first_name>
			<surname>Dooley</surname>
    </name>

		<details>
			<address>
				<number_or_name>11</number_or_name>
				<street>Killeen Crescent</street>
				<town>Malahide</town>
				<postcode>K36 X368</postcode>
				<county>Dublin</county>
			</address>

			<PPSN>8782192M</PPSN>
			<phone_number>0860721926</phone_number>
			<e-mail_address>dooleyb1@tcd.ie</e-mail_address>
			
			<bank_details>
				<IBAN>1271MA192739</IBAN>
				<BIC>2718AX</BIC>
			</bank_details>	
		</details>

		<role>Junior Mechanic</role>
			
		<vehicles_serviced>
			<Vehicle vehicle_id ="19210">
				<type>Ambulance</type>
				<last_service>21/06/2016</last_service>
				<needs_service>false</needs_service>
				<is_being_serviced>false</is_being_serviced>
			</Vehicle>

			<Vehicle vehicle_id ="97315">
				<type>Fire Brigade</type>
				<last_service>31/12/2014</last_service>
				<needs_service>true</needs_service>
				<is_being_serviced>false</is_being_serviced>
			</Vehicle>

			<Vehicle vehicle_id ="4287">
				<type>Police Car</type>
				<last_service>19/5/2017</last_service>
				<needs_service>false</needs_service>
				<is_being_serviced>false</is_being_serviced>
			</Vehicle>
		</vehicles_serviced>
		
		<is_servicing>false</is_servicing>
	</Mechanic>
</Mechanics_Info>
