=== dooleyb1/secondyear/mt/infoman_cs2041/assignments/assignment_2_XML/XML Files/parts_inventory.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- This document contains the design for a file containing parts inventory data. -->
<!-- The parts inventory contains a list of all parts in stock, information pertaining
the parts and stock figures. -->
<!ELEMENT partsInventory (part+)>

<!-- Each part with a unique part id has its own part entry. The id is entered as an attribute,
as is the category of the part and the no. of that part in stock. Make, model, name and part
description are all required elements for each part. ? is used for all others as they are
not required but can only occur a maximum of once. -->
<!ELEMENT part (make,model,name,partDescription,fittingPosition?,RRP?,specification?)>
<!ATTLIST part id CDATA #REQUIRED>
<!ATTLIST part category CDATA "uncategorized">
<!ATTLIST part stock CDATA #REQUIRED>

<!-- Make and model are required elements for each part and the model has a required attribute
to specify the model years for the part. -->
<!ELEMENT make (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ATTLIST model year CDATA #REQUIRED>

<!-- The name and part description are also required for each part entry. -->
<!ELEMENT name (#PCDATA)>
<!ELEMENT partDescription (#PCDATA)>

<!-- Fitting position allows to specify which part of the vehicle the part is to be fitted to -->
<!ELEMENT fittingPosition (#PCDATA)>

<!-- RRP specifies the recommended retail price as reference for mechanics as to what a
reasonable price to pay and charge for a part is. The currency attribute can also be
specified and its default is euro. -->
<!ELEMENT RRP (#PCDATA)>
<!ATTLIST RRP currency CDATA "euro">

<!-- The specification element is used to provide important part specific information to a mechanic. -->
<!-- Some elements such as height and diameters have a metric attribute to specify the unit of measurement -->
<!-- All elements have a cardinality of ? as they are all optional elements but may only occur a maximum of once-->
<!ELEMENT specification (height?,inlet?,outerDiameter?,innerDiameter?,shape?,transmissionType?,engineCode?,weight?)>
<!ELEMENT height (#PCDATA)>
<!ATTLIST height metric CDATA "mm">

<!ELEMENT inlet (#PCDATA)>
<!ATTLIST inlet metric CDATA "mm">

<!ELEMENT outerDiameter (#PCDATA)>
<!ATTLIST outerDiameter metric CDATA "mm">

<!ELEMENT innerDiameter (#PCDATA)>
<!ATTLIST innerDiameter metric CDATA "mm">

<!ELEMENT shape (#PCDATA)>
<!ELEMENT transmissionType (#PCDATA)>
<!ELEMENT engineCode (#PCDATA)>

<!ELEMENT weight (#PCDATA)>
<!ATTLIST weight metric CDATA "kg">

=== dooleyb1/secondyear/exams/information_management_cs2041/xml_files/mechanics_assignment/parts_inventory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE partsInventory SYSTEM "parts_inventory.dtd">
<partsInventory>
    <part id="6582092" category="brakes" stock="12">
        <make>ford</make>
        <model year="1995-2000">transit</model>
        <name>Master-Sport Brake Discs (pair)</name>
        <partDescription>To fit ford transit From Jan 1995 to Nov 2000 1.8[125hp 1781cc]</partDescription>
        <fittingPosition>front axle</fittingPosition>
        <RRP currency="euro">58.16</RRP>
    </part>
    <part id="1492666" category="filters" stock="5">
        <make>mercedes</make>
        <model year="1982-1992">sprinter</model>
        <name>Mann Fuel Filter</name>
        <partDescription>To fit Mercedes Sprinter from Sep 1982 to Mar 1992 316i[100hp 1596cc]</partDescription>
        <RRP currency="euro">20.99</RRP>
        <specification>
            <height metric="mm">164</height>
            <inlet metric="mm"></inlet>
            <outerDiameter metric="mm">74</outerDiameter>
        </specification>
    </part>
    <part id="1701812" category="filters" stock="5">
        <make>hyundai</make>
        <model year="2002-2009">i40</model>
        <name>Wix Filtron Air Filter</name>
        <partDescription>
            To fit Hyundai i40 from Mar 2011 to Dec 2016 E220 CDI 
            (211.008)[170hp. 2148cc]
        </partDescription>
        <RRP currency="euro">22.99</RRP>
        <specification>
            <height metric="mm">434</height>
            <outerDiameter metric="mm">120</outerDiameter>
            <innerDiameter metric="mm">70</innerDiameter>
            <shape>round</shape>
        </specification>
    </part>
    <part id="1904414" category="clutch" stock="2">
        <make>audi</make>
        <model year="2003-2009">q7</model>
        <name>Valeo Clutch Kit</name>
        <partDescription>
            To fit Audi Q7 from Oct 2015 to Feb 2017 2.0 
            GTI[200hp 1984cc.]
        </partDescription>
        <RRP currency="euro">377.99</RRP>
        <specification>
            <transmissionType>manual</transmissionType>
            <engineCode>CDLG</engineCode>
            <weight metric="kg">6.88</weight>
        </specification>
    </part>
    <part id="49381405" category="tyres" stock="20">
        <make>ford</make>
        <model year="2003-2009">transit</model>
        <name>Low profile Continental Tyre</name>
        <partDescription>
            To fit Ford Transit from Oct 2015 to Feb 2017 2.0 
            GTI[200hp 1984cc.]
        </partDescription>
        <RRP currency="euro">79.99</RRP>
    </part>
    <part id="4959383" category="gearbox" stock="1">
        <make>mercedes</make>
        <model year="2003-2009">sprinter</model>
        <name>Mercedes Sprinter replacement gearbox</name>
        <partDescription>
            To fit Mercedes Sprinter from Oct 2015 to Feb 2017 2.0 
            GTI[200hp 1984cc.]
        </partDescription>
        <RRP currency="euro">459.99</RRP>
    </part>
</partsInventory>
