=== dooleyb1/secondyear/mt/information_management_cs2041/assignments/assignment_2_XML/XML Files/repairs.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- This document contains the design for a file containing vehicle repairs data. -->

<!ELEMENT repairs (repair+)>
 <!-- Not all repairs will have parts needed so it is marked with ? cardinality. -->
<!ELEMENT repair (vehicleID, repairDescription, repairType, partsNeeded?)>
<!ATTLIST repair id CDATA #REQUIRED>
<!ELEMENT vehicleID (#PCDATA)>

<!ELEMENT repairDescription (#PCDATA)>
<!ELEMENT repairType (#PCDATA)>
<!-- Each parts needed contains parts elements with id attributes and quantity attributes.
The id attribute is required and the default quantity is 1 -->
<!ELEMENT partsNeeded (part+)>
<!ELEMENT part EMPTY>
<!ATTLIST part id CDATA #REQUIRED>
<!ATTLIST part quantity CDATA "1">

=== dooleyb1/secondyear/mt/infoman_cs2041/assignments/assignment_2_XML/XML Files/repairs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE repairs SYSTEM "repairs.dtd">
<repairs>
    <repair id="5689">
        <vehicleID>2019</vehicleID>
        <repairDescription>Flat tyres</repairDescription>
        <repairType>Part replacement</repairType>
        <partsNeeded>
            <part id="49381405" quantity="4" />
        </partsNeeded>
    </repair>
    <repair id="140596">
        <vehicleID>4930</vehicleID>
        <repairDescription>Door lock on passenger door broken</repairDescription>
        <repairType>Part repair</repairType>
    </repair>
    <repair id="1458">
        <vehicleID>13984</vehicleID>
        <repairDescription>broken gear box</repairDescription>
        <repairType>Part Replacment</repairType>
        <partsNeeded>
            <part id="4959383" quantity="1" />
        </partsNeeded>
    </repair>
</repairs>
