=== dooleyb1/secondyear/mt/information_management_cs2041/assignments/assignment_2_XML/XML Files/vehicle_maintenance.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- This document contains the design for a file containing vehicle maintenance data. -->
<!-- The parts inventory contains a list of all services to be completed, information pertaining
the service and mechanic assigned to the service. The + cardinality is used for service as
there must be one but there can be as many as needed -->
<!ELEMENT vehicleMaintenance (service*, repair*)>

<!-- Each service contains important information for the mechanic. The vehicle ID is required,
however the mechanic ID is not (marked with ? cardinality). This is because the service could 
be added without a mechanic initially assigned to it. The same goes for parts needed. There
may not always be parts needed to complete the service. -->
<!-- The service ID is an attribute to the service element -->
<!ELEMENT service (isBeingServiced, mechanics?, priority?, dueDate?)>
<!ATTLIST service id CDATA #REQUIRED>

<!-- Each repair contains important information for the mechanic. The vehicle ID is required,
however the mechanic ID is not (marked with ? cardinality). This is because the repair could 
be added without a mechanic initially assigned to it. The same goes for parts needed. There
may not always be parts needed to complete the repair. -->
<!-- The repair ID is an attribute to the service element -->
<!ELEMENT repair (isBeingRepaired, mechanics?, priority?, dueDate?)>
<!ATTLIST repair id CDATA #REQUIRED>

<!ELEMENT isBeingRepaired (#PCDATA)>

<!ELEMENT isBeingServiced (#PCDATA)>
<!ELEMENT mechanics (mechanicID+)>
<!ELEMENT priority (#PCDATA)>
<!ELEMENT dueDate (#PCDATA)>

<!ELEMENT mechanicID (#PCDATA)>

=== dooleyb1/secondyear/exams/information_management_cs2041/xquery_files/mechanics_assignment/vehicle_maintenance.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vehicleMaintenance SYSTEM "vehicle_maintenance.dtd">
<vehicleMaintenance>

    <service id="40292">
        <isBeingServiced>No</isBeingServiced>
        <mechanics>
            <mechanicID>40391</mechanicID>
        </mechanics>
        <priority>high</priority>
        <dueDate>21-1-2018</dueDate>
    </service>

    <service id="402918">
        <isBeingServiced>YES</isBeingServiced>
        <mechanics>
            <mechanicID>40393</mechanicID>
        </mechanics>
        <priority>low</priority>
        <dueDate>12-2-2018</dueDate>
    </service>

    <service id="30291">
        <isBeingServiced>NO</isBeingServiced>
        <mechanics>
            <mechanicID>24829</mechanicID>
        </mechanics>
        <priority>medium</priority>
        <dueDate>12-12-2017</dueDate>
    </service>

    <repair id="5689">
        <isBeingRepaired>NO</isBeingRepaired>
        <priority>low</priority>
        <dueDate>15-12-2017</dueDate>
    </repair>

    <repair id="140596">
        <isBeingRepaired>YES</isBeingRepaired>
        <mechanics>
            <mechanicID>40392</mechanicID>
            <mechanicID>40394</mechanicID>
        </mechanics>
        <priority>high</priority>
        <dueDate>8-12-2017</dueDate>
    </repair>

    <repair id="1458">
        <isBeingRepaired>NO</isBeingRepaired>
        <priority>high</priority>
        <dueDate>10-12-2017</dueDate>
    </repair>
    
</vehicleMaintenance>
