=== dooleyb1/secondyear/exams/information_management_cs2041/xquery_files/mechanics_assignment/Admin_Info.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- This document contains the XML Model for the info of all Admins within the larger Emergency Services Vehicle Maintenance System model -->

<!--  The + cardinality is used for Admin as there must be at least one Admin registered in the system or an infinite amount of Admins-->

<!ELEMENT Admin_Info (Admin)+>

<!-- Each Admin has a required attribute 'user_id', so if any changes are made to the system the ID of the Admin can be used as a reference. Each Admin can have multiple roles however must have at least one, hence the + cardinality is used. The cardinality * is used for 'user_privileges' as if no priveleges are specified, the Admin has root access to everything in the system. -->

<!ELEMENT Admin (user_name, user_role+, user_privileges*)>
<!ATTLIST Admin user_id CDATA #REQUIRED>
<!ELEMENT user_id (#PCDATA)>

<!ELEMENT user_name   (first_name, surname)>
		<!ELEMENT first_name (#PCDATA)>
		<!ELEMENT surname (#PCDATA)>
<!ELEMENT user_role (#PCDATA)>

<!-- The user privileges 'mechanic_ids' and 'vehicle_ids' has the cardinality ? as not all Admins necessarily have access to both or any of them. 'mechanic_id' and 'vehicle_id' has the cardinality + as there must be at least one of each in the database.  -->

<!ELEMENT user_privileges (mechanic_ids?, vehicle_ids?)>
		<!ELEMENT mechanic_ids (mechanic_id+)>
			<!ELEMENT mechanic_id (#PCDATA)>
		<!ELEMENT vehicle_ids (vehicle_id+)>
			<!ELEMENT vehicle_id (#PCDATA)>

=== dooleyb1/secondyear/mt/information_management_cs2041/assignments/assignment_2_XML/XML Files/Admin_Info.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Admin_Info SYSTEM "Admin_Info.dtd">

<Admin_Info>
	<Admin  user_id="102">
	    <user_name>
			<first_name>Jim</first_name>
			<surname>Ryan</surname>
		</user_name>
		<user_role>System security</user_role>
		<user_privileges>
		<mechanic_ids>
			<mechanic_id>40391</mechanic_id>
			<mechanic_id>40392</mechanic_id>
			<mechanic_id>40393</mechanic_id>
			<mechanic_id>40394</mechanic_id>
			<mechanic_id>24829</mechanic_id>
		</mechanic_ids>
		<vehicle_ids>
			<vehicle_id>2019</vehicle_id>
			<vehicle_id>4930</vehicle_id>
			<vehicle_id>13984</vehicle_id>
			<vehicle_id>1246</vehicle_id>
			<vehicle_id>4958</vehicle_id>
		</vehicle_ids>
		</user_privileges>
	</Admin>

	<Admin user_id="202">
		<user_name>
			<first_name>Timmy</first_name>
			<surname>Bob</surname>
		</user_name>
		<user_role>System maintenance</user_role>
		<user_privileges>
			<mechanic_ids>
				<mechanic_id>40391</mechanic_id>
				<mechanic_id>40392</mechanic_id>
				<mechanic_id>40393</mechanic_id>
				<mechanic_id>40394</mechanic_id>
				<mechanic_id>24829</mechanic_id>
			</mechanic_ids>
			<vehicle_ids>
				<vehicle_id>2019</vehicle_id>
				<vehicle_id>4930</vehicle_id>
				<vehicle_id>13984</vehicle_id>
				<vehicle_id>1246</vehicle_id>
				<vehicle_id>4958</vehicle_id>
			</vehicle_ids>
		</user_privileges>
	</Admin>

	<Admin user_id="105">
		<user_name>
			<first_name>Fergus</first_name>
			<surname>Moyles</surname>
		</user_name>
		<user_role>Trainee Admin</user_role>
		<user_privileges>
		<vehicle_ids>
			<vehicle_id>2019</vehicle_id>
			<vehicle_id>4930</vehicle_id>
			<vehicle_id>13984</vehicle_id>
			<vehicle_id>1246</vehicle_id>
			<vehicle_id>4958</vehicle_id>
		</vehicle_ids>
		</user_privileges>
	</Admin>
</Admin_Info>
