=== dooleyb1/secondyear/exams/information_management_cs2041/xquery_files/mechanics_assignment/mechanics_info.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- This document contains the XML Model for the records/info of all mechanics within the larger Emergency Services Vehicle Maintenance System model -->

<!--  The * cardinality is used for Mechanic as there can be no mechanics registered in the system or an infinite amount of mechanics-->

<!ELEMENT Mechanics_Info (Mechanic)*>

<!-- Each mechanic has an associated set of data attributed to the mechanic itself. Each mechanic has a required attribute 'mechanic_id', this is so anyone operating on the system can effeciently and quickly access/edit a mechanics respective details. Each mechanic can have multiple roles however must have atleast one, hence the + cardinality is used. -->

<!ELEMENT Mechanic (name, details, role+, vehicles_serviced, is_servicing)>
<!ATTLIST Mechanic mechanic_id CDATA #REQUIRED>
<!ELEMENT mechanic_id (#PCDATA)>

<!ELEMENT name   (first_name,surname)>
		<!ELEMENT first_name (#PCDATA)>
		<!ELEMENT surname (#PCDATA)>

<!ELEMENT details (address, PPSN, phone_number, e-mail_address, bank_details)>
		<!ELEMENT address (number_or_name, street, town, postcode, county)>
				<!ELEMENT number_or_name (#PCDATA)>
				<!ELEMENT street (#PCDATA)>
				<!ELEMENT town (#PCDATA)>
				<!ELEMENT postcode (#PCDATA)>	
				<!ELEMENT county (#PCDATA)>
		<!ELEMENT PPSN (#PCDATA)>
		<!ELEMENT phone_number (#PCDATA)>
		<!ELEMENT e-mail_address (#PCDATA)>
		<!ELEMENT bank_details (IBAN, BIC)>
				<!ELEMENT IBAN (#PCDATA)>
				<!ELEMENT BIC (#PCDATA)>
<!ELEMENT role (#PCDATA)>

<!-- Each mechanic also has an associated record of all the vehicles he/she has previously serviced. This is to enable a sense of traceability to the system, so that in the event of an accident occuring as a direct result of a faulty service the full service history can be traced back. -->

<!ELEMENT vehicles_serviced (Vehicle)*>

<!-- Each vehicle has associated required attributes 'VehicleID', 'NeedsService', 'isBeingServiced' this is in place to allow effecient and quick access to a vehicles record by someone acting on the system. Each vehicle also has other pieces of data associated with it such as when it was last serviced, whether or not it needs a service and whether or not it is currently being serviced. -->

		<!ELEMENT Vehicle (VehicleDetails, LastService)>
			<!ATTLIST Vehicle VehicleID CDATA #REQUIRED>
			<!ATTLIST Vehicle NeedsService CDATA #REQUIRED>
			<!ATTLIST Vehicle isBeingServiced CDATA #REQUIRED>
			<!ELEMENT VehicleID (#PCDATA)>
			<!ELEMENT NeedsService (#PCDATA)>
			<!ELEMENT isBeingServiced (#PCDATA)>
			<!ELEMENT LastService (#PCDATA)>

<!ELEMENT is_servicing (#PCDATA)>

=== dooleyb1/secondyear/exams/information_management_cs2041/xml_files/mechanics_info.XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Mechanics_Info SYSTEM "mechanics_info.dtd">

<Mechanics_Info>
  <Mechanic  mechanic_id="40391">
    <name>
			<first_name>Marsha</first_name>
			<surname>Knight</surname>
    </name>

		<details>
			<address>
				<number_or_name>The Orchard</number_or_name>
				<street>Pinehill Letterkenny</street>
				<town>Letterkenny</town>
				<postcode>B21 U819</postcode>
				<county>Donegal</county>
			</address>

			<PPSN>8218290C</PPSN>
			<phone_number>0831821336</phone_number>
			<e-mail_address>knightMarsh2@gmail.com</e-mail_address>
			
			<bank_details>
				<IBAN>28191CBOIJ129</IBAN>
				<BIC>61BOI2910</BIC>
			</bank_details>	
		</details>

		<role>Senior Mechanic</role>
			
		<vehicles_serviced>
			<Vehicle VehicleID='4930' NeedsService="YES" isBeingServiced="NO">
				<LastService>21/06/2017</LastService>
 			 </Vehicle>

			<Vehicle VehicleID="2019" NeedsService="YES" isBeingServiced="YES">
				<LastService>14/03/2016</LastService>
  			</Vehicle>
			
			<Vehicle VehicleID="13984" NeedsService="NO" isBeingServiced="NO">
				<LastService>9/11/2017</LastService>
 			 </Vehicle>

			  <Vehicle VehicleID="1246" NeedsService="NO" isBeingServiced="NO">
				    <LastService>31/9/2017</LastService>
 			 </Vehicle>

			 <Vehicle VehicleID="4958" NeedsService="YES" isBeingServiced="YES">
			            <LastService>23/8/2015</LastService>
 			 </Vehicle>
		</vehicles_serviced>

		<is_servicing>false</is_servicing>
    </Mechanic>


    <Mechanic  mechanic_id="40392">
		<name>
			<first_name>Mark</first_name>
			<surname>O'Sullivan</surname>
		</name>

		<details>
			<address>
				<number_or_name>21</number_or_name>
				<street>Seabury Crescent</street>
				<town>Malahide</town>
				<postcode>K28 C910</postcode>
				<county>Dublin</county>
			</address>

			<PPSN>48183990D</PPSN>
			<phone_number>0851309736</phone_number>
			<e-mail_address>mark.osul@yahoo.com</e-mail_address>
			
			<bank_details>
				<IBAN>73491CAIBK129</IBAN>
				<BIC>10AIB2910</BIC>
			</bank_details>	
		</details>

		<role>Junior Mechanic</role>
			
		<vehicles_serviced>
			<Vehicle VehicleID="1246" NeedsService="NO" isBeingServiced="NO">
				 <LastService>31/9/2017</LastService>
 			 </Vehicle>
		</vehicles_serviced>
		<is_servicing>false</is_servicing>
    </Mechanic>

    <Mechanic  mechanic_id="40393">
		<name>
			<first_name>Tim</first_name>
			<surname>Stanley</surname>
		</name>

		<details>
			<address>
				<number_or_name>95</number_or_name>
				<street>Drimnagh Woods</street>
				<town>Castlenock</town>
				<postcode>W72 G731</postcode>
				<county>Dublin</county>
			</address>

			<PPSN>38823938P</PPSN>
			<phone_number>0862279106</phone_number>
			<e-mail_address>timmystan@live.co.uk</e-mail_address>
			
			<bank_details>
				<IBAN>10036CABOI190</IBAN>
				<BIC>93BOI2170</BIC>
			</bank_details>	
		</details>

		<role>Senior Mechanic</role>
			
		<vehicles_serviced>
			<Vehicle VehicleID='4930' NeedsService="YES" isBeingServiced="NO">
				<LastService>21/06/2017</LastService>
 			 </Vehicle>

			<Vehicle VehicleID="2019" NeedsService="YES" isBeingServiced="YES">
				<LastService>14/03/2016</LastService>
  			</Vehicle>
			
			<Vehicle VehicleID="13984" NeedsService="NO" isBeingServiced="NO">
				<LastService>9/11/2017</LastService>
 			 </Vehicle>

			  <Vehicle VehicleID="1246" NeedsService="NO" isBeingServiced="NO">
				    <LastService>31/9/2017</LastService>
 			 </Vehicle>

			 <Vehicle VehicleID="4958" NeedsService="YES" isBeingServiced="YES">
			            <LastService>23/8/2015</LastService>
 			 </Vehicle>
		</vehicles_serviced>
		<is_servicing>true</is_servicing>
    </Mechanic>

    <Mechanic  mechanic_id="40394">
    		<name>
			<first_name>Bob</first_name>
			<surname>Curtis</surname>
    		</name>

		<details>
			<address>
				<number_or_name>92</number_or_name>
				<street>Streamstown Lane</street>
				<town>Swords</town>
				<postcode>H37 X198</postcode>
				<county>Dublin</county>
			</address>

			<PPSN>72593702K</PPSN>
			<phone_number>0837703126</phone_number>
			<e-mail_address>bobbycurtis420@gmail.com</e-mail_address>
			
			<bank_details>
				<IBAN>N/A</IBAN>
				<BIC>N/A</BIC>
			</bank_details>	
		</details>

		<role>Intern</role>
			
		<vehicles_serviced>
		</vehicles_serviced>
		<is_servicing>false</is_servicing>
    </Mechanic>

    <Mechanic  mechanic_id="40395">
    		<name>
			<first_name>Willie</first_name>
			<surname>Walsh</surname>
    		</name>

		<details>
			<address>
				<number_or_name>47</number_or_name>
				<street>Raglan Road</street>
				<town>Ballybough</town>
				<postcode>B42 U829</postcode>
				<county>Dublin</county>
			</address>

			<PPSN>14228602Z</PPSN>
			<phone_number>08912304126</phone_number>
			<e-mail_address>williewalsher@yahoo.com</e-mail_address>
			
			<bank_details>
				<IBAN>26937CAIBK365</IBAN>
				<BIC>64AIB4137</BIC>
			</bank_details>	
		</details>

		<role>Apprentice Mechanic</role>
			
		<vehicles_serviced>
			<Vehicle VehicleID="1246" NeedsService="NO" isBeingServiced="NO">
				    <LastService>31/9/2017</LastService>
 			 </Vehicle>
		</vehicles_serviced>
		<is_servicing>true</is_servicing>
    </Mechanic>

</Mechanics_Info>
