=== dooleyb1/secondyear/exams/information_management_cs2041/xquery_files/mechanics_assignment/services.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- This document contains the design for a file containing vehicle maintenance data. -->
<!-- The parts inventory contains a list of all services to be completed, information pertaining
the service and mechanic assigned to the service. The + cardinality is used for service as
there must be one but there can be as many as needed -->
<!ELEMENT services (service+)>

<!-- Each service contains important information for the mechanic. The vehicle ID is required,
however the mechanic ID is not (marked with ? cardinality). This is because the service could 
be added without a mechanic initially assigned to it. The same goes for parts needed. There
may not always be parts needed to complete the service. -->
<!-- The service ID is an attribute to the service element -->
<!ELEMENT service (vehicleID, mechanicID?, serviceDescription, serviceType, partsNeeded?)>
<!ATTLIST service id CDATA #REQUIRED>

<!ELEMENT vehicleID (#PCDATA)>
<!ELEMENT mechanicID (#PCDATA)>
<!ELEMENT serviceDescription (#PCDATA)>
<!ELEMENT serviceType (#PCDATA)>

<!-- Each parts needed contains parts elements with id attributes and quantity attributes.
The id attribute is required and the default quantity is 1 -->
<!ELEMENT partsNeeded (part+)>
<!ELEMENT part EMPTY>
<!ATTLIST part id CDATA #REQUIRED>
<!ATTLIST part quantity CDATA "1">

=== dooleyb1/secondyear/exams/information_management_cs2041/xquery_files/mechanics_assignment/services.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE services SYSTEM "services.dtd">
<services>
    <service id="40292">
            <vehicleID>2019</vehicleID>
            <mechanicID>40391</mechanicID>
            <serviceDescription>
                Regular minor service maintenance. New front and rear disk breaks also needed.
            </serviceDescription>
            <serviceType>Minor Service</serviceType>
            <partsNeeded>
                <part id="6582092" quantity="2" />
                <part id="1492666" />
            </partsNeeded>
        </service>
        <service id="402918">
            <vehicleID>13984</vehicleID>
            <mechanicID>40393</mechanicID>
            <serviceDescription>
                Regular major service at 150,000 km. Drivers complaining of vehicle pulling
                to the left at higher speeds. Check as part of major service
            </serviceDescription>
            <serviceType>Major Service</serviceType>
        </service>
        <service id="30291">
            <vehicleID>1246</vehicleID>
            <mechanicID>24829</mechanicID>
            <serviceDescription>
                New air and fuel filters need to be fitted as well as major service
            </serviceDescription>
            <serviceType>Minor Service</serviceType>
            <partsNeeded>
                <part id="1492666" quantity="3" />
                <part id="1701812" />
            </partsNeeded>
        </service>
    </services>
